version: '3'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:16
    container_name: dw_pg
    environment:
      POSTGRES_DB: dw_tiki
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "35432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  minio_data: